[build]
  command = "composer install && composer run-script post-install-cmd && composer run-script post-create-project-cmd"
  publish = "public"

[build.environment]
  APP_KEY = "${APP_KEY}"
  APP_STORAGE = "./storage"
  VIEW_COMPILED_PATH = "./storage/framework/views"
  CACHE_DRIVER = "array"
  SESSION_DRIVER = "array"
  QUEUE_DRIVER = "sync"
